{% set name = "coverage-conditional-plugin" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coverage-conditional-plugin-{{ version }}.tar.gz
  sha256: 3ca50bb03b32f8ba8cf63b18d830f334cb75f401579040dd5c61df1c4687fef0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.0
    - python {{ python_min }}
  run:
    - coverage >=5.0,<6.0
    - packaging >=20.4
    - python >={{ python_min }},<4.0

test:
  imports:
    - coverage_conditional_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wemake-services/coverage-conditional-plugin
  summary: Conditional coverage based on any rules you define!
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/wemake-services/coverage-conditional-plugin

extra:
  recipe-maintainers:
    - tarcisioe
